export const LOAD_TODOS_START = 'LOAD_TODOS_START';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCES';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCES';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
